package POJOS;
// Generated May 4, 2021 4:52:18 PM by Hibernate Tools 4.3.1



/**
 * Coursedetails generated by hbm2java
 */
public class Coursedetails  implements java.io.Serializable {


     private String courseid;
     private Faculty faculty;
     private User user;
     private String coursename;
     private String description;
     private Double coursepayment;
     private String courseurl;
     private Integer status;
     private String unid;

    public Coursedetails() {
    }

	
    public Coursedetails(String courseid, Faculty faculty, User user, String courseurl, String unid) {
        this.courseid = courseid;
        this.faculty = faculty;
        this.user = user;
        this.courseurl = courseurl;
        this.unid = unid;
    }
    public Coursedetails(String courseid, Faculty faculty, User user, String coursename, String description, Double coursepayment, String courseurl, Integer status, String unid) {
       this.courseid = courseid;
       this.faculty = faculty;
       this.user = user;
       this.coursename = coursename;
       this.description = description;
       this.coursepayment = coursepayment;
       this.courseurl = courseurl;
       this.status = status;
       this.unid = unid;
    }
   
    public String getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCoursename() {
        return this.coursename;
    }
    
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getCoursepayment() {
        return this.coursepayment;
    }
    
    public void setCoursepayment(Double coursepayment) {
        this.coursepayment = coursepayment;
    }
    public String getCourseurl() {
        return this.courseurl;
    }
    
    public void setCourseurl(String courseurl) {
        this.courseurl = courseurl;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getUnid() {
        return this.unid;
    }
    
    public void setUnid(String unid) {
        this.unid = unid;
    }




}


