package POJOS;
// Generated May 4, 2021 4:52:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Distric generated by hbm2java
 */
public class Distric  implements java.io.Serializable {


     private String disid;
     private String disname;
     private Set<Faculty> faculties = new HashSet<Faculty>(0);

    public Distric() {
    }

	
    public Distric(String disid) {
        this.disid = disid;
    }
    public Distric(String disid, String disname, Set<Faculty> faculties) {
       this.disid = disid;
       this.disname = disname;
       this.faculties = faculties;
    }
   
    public String getDisid() {
        return this.disid;
    }
    
    public void setDisid(String disid) {
        this.disid = disid;
    }
    public String getDisname() {
        return this.disname;
    }
    
    public void setDisname(String disname) {
        this.disname = disname;
    }
    public Set<Faculty> getFaculties() {
        return this.faculties;
    }
    
    public void setFaculties(Set<Faculty> faculties) {
        this.faculties = faculties;
    }




}


