package POJOS;
// Generated May 4, 2021 4:52:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private String facid;
     private Distric distric;
     private University university;
     private String facname;
     private int status;
     private Set<Coursedetails> coursedetailses = new HashSet<Coursedetails>(0);

    public Faculty() {
    }

	
    public Faculty(String facid, Distric distric, University university, int status) {
        this.facid = facid;
        this.distric = distric;
        this.university = university;
        this.status = status;
    }
    public Faculty(String facid, Distric distric, University university, String facname, int status, Set<Coursedetails> coursedetailses) {
       this.facid = facid;
       this.distric = distric;
       this.university = university;
       this.facname = facname;
       this.status = status;
       this.coursedetailses = coursedetailses;
    }
   
    public String getFacid() {
        return this.facid;
    }
    
    public void setFacid(String facid) {
        this.facid = facid;
    }
    public Distric getDistric() {
        return this.distric;
    }
    
    public void setDistric(Distric distric) {
        this.distric = distric;
    }
    public University getUniversity() {
        return this.university;
    }
    
    public void setUniversity(University university) {
        this.university = university;
    }
    public String getFacname() {
        return this.facname;
    }
    
    public void setFacname(String facname) {
        this.facname = facname;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set<Coursedetails> getCoursedetailses() {
        return this.coursedetailses;
    }
    
    public void setCoursedetailses(Set<Coursedetails> coursedetailses) {
        this.coursedetailses = coursedetailses;
    }




}


