package POJOS;
// Generated May 4, 2021 4:52:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String userid;
     private String name;
     private String mobile;
     private String email;
     private String password;
     private Integer status;
     private Set<Coursedetails> coursedetailses = new HashSet<Coursedetails>(0);

    public User() {
    }

	
    public User(String userid) {
        this.userid = userid;
    }
    public User(String userid, String name, String mobile, String email, String password, Integer status, Set<Coursedetails> coursedetailses) {
       this.userid = userid;
       this.name = name;
       this.mobile = mobile;
       this.email = email;
       this.password = password;
       this.status = status;
       this.coursedetailses = coursedetailses;
    }
   
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<Coursedetails> getCoursedetailses() {
        return this.coursedetailses;
    }
    
    public void setCoursedetailses(Set<Coursedetails> coursedetailses) {
        this.coursedetailses = coursedetailses;
    }




}


